POST /v1/auth/refresh-tokens HTTP/1.1
Host: localhost:3000
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjEwMGViYTZiNDIwNWZjNjFlNWNjMTAiLCJpYXQiOjE2NDUyMjA0MjEsImV4cCI6MTY0NTIyMjIyMSwidHlwZSI6ImFjY2VzcyJ9.wUyMrEoZg_hkkB6OHAC5w3AMRt0gihZzEGmLfsUy_zo

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjEwMGViYTZiNDIwNWZjNjFlNWNjMTAiLCJpYXQiOjE2NDUyMjA0MjEsImV4cCI6MTY0NzgxMjQyMSwidHlwZSI6InJlZnJlc2gifQ.BTLN0DRlEHXMKlVT4OKipnq4eCpwBUcOVo9ogBPAFRI"
}
