GET /v1/abclists/ HTTP/1.1
Host: localhost:3000
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjEwMTUwY2QxZGE0ODAwYzIwNTA0OTMiLCJpYXQiOjE2NDUyNjM5MTYsImV4cCI6MTY0NTI2NTcxNiwidHlwZSI6ImFjY2VzcyJ9.qKEg3NtcOhdFvph-U5NU4ZIyyM39jyD8JqBzlefOFFE
