GET /v1/abclists/6218012bf6683b15d099611f HTTP/1.1
Host: localhost:3000
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjEwMTUwY2QxZGE0ODAwYzIwNTA0OTMiLCJpYXQiOjE2NDU5NTcxNjQsImV4cCI6MTY0NTk1ODk2NCwidHlwZSI6ImFjY2VzcyJ9.mi_7dRfs4s-tVRr3Fk3ffCjt_iu-Jtm9nT8kixXcQh4
